print ("hello world")
print ("second commit")
print ("third commit")
print ("fourth commit")
print ("fifth commit from github online; now checking to see if VS code pulls the changes")
print ("sixth commit from github online; now checking to see if VS code will sync")
print ("seventh commit in order to check if VS code can sync it's commits to github online")
print (error)